name: dw-clone

on: [push]

env:
  NILE_DEVELOPER_EMAIL: ${{ secrets.NILE_DEVELOPER_EMAIL }}
  NILE_DEVELOPER_PASSWORD: ${{ secrets.NILE_DEVELOPER_PASSWORD }}

jobs:

  quickstart:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: -cwd ./dw-clone install

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: -cwd ./dw-clone setup
