name: dw-clone

on: [push]

env:
  NILE_DEVELOPER_EMAIL: ${{ secrets.NILE_DEVELOPER_EMAIL }}
  NILE_DEVELOPER_PASSWORD: ${{ secrets.NILE_DEVELOPER_PASSWORD }}

jobs:

  quickstart:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Run yarn setup
        #run: |
          #cd dw-clone
          #yarn install
          #yarn add node-fetch
          #yarn setup

      - name: Set node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./dw-clone install

      - name: yarn add node-fetch
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./dw-clone add node-fetch

      - name: yarn setup
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./dw-clone setup
