name: examples

on: [push]

env:
  NILE_DEVELOPER_EMAIL: ${{ secrets.NILE_DEVELOPER_EMAIL }}
  NILE_DEVELOPER_PASSWORD: ${{ secrets.NILE_DEVELOPER_PASSWORD }}

jobs:

  dw-clone:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Run yarn setup
        #run: |
          #cd dw-clone
          #yarn install
          #yarn add node-fetch
          #yarn setup

      - name: Set node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: yarn install
        working-directory: dw-clone
        run: yarn install --no-lockfile

      - name: yarn add node-fetch
        working-directory: dw-clone
        run: yarn add node-fetch --no-lockfile

      - name: yarn setup
        working-directory: dw-clone
        run: timeout 15s yarn setup
